[package]
name = "whkd-parser"
description = "A parser for whkd"
version.workspace = true
repository.workspace = true
edition.workspace = true

[dependencies]
whkd-core.workspace = true
chumsky.workspace = true
thiserror = "2"