[package]
name = "whkd_parser"
description = "A parser for whkd"
version.workspace = true
repository.workspace = true
edition.workspace = true

[dependencies]
whkd_core.workspace = true
chumsky.workspace = true
